name: Generador Noche Pro
on:
  workflow_dispatch:
  repository_dispatch:
    types: [start_mining]

jobs:
  generar:
    runs-on: ubuntu-latest
    steps:
      - name: Laburo
        run: |
          python3 -c "print('NexoraSaaS activo')"
