name: NexoraSaaS Infinity Pass Stream
on:
  workflow_dispatch:
  repository_dispatch:
    types: [start_mining]

jobs:
  stream_passwords:
    runs-on: ubuntu-latest
    steps:
      - name: Generacion Masiva y Envio Directo
        run: |
          python3 -c "
          import random, time, requests, os, zipfile
          TOKEN_TG = '8575399229:AAHBcjak2HSG3uoA1_yA64zJ3P0b0C9p0p4'
          CHAT_ID = '7210756206'
          
          # Patrones basados en ataques reales a Comcast
          temas = ['Summer', 'Bella', 'Logan', 'Welcome', 'Jordan', 'Hunter', 'Charlie', 'Baseball', 'Soccer', 'Family', 'Jesus', 'Godisgood', 'Password', 'Redsox', 'Apples', 'Cookie', 'Softball', 'Builders', 'Survivor', 'King']
          simbolos = ['!', '!!', '$', '$$', '@', '#', '!@#$']
          anios = [str(x) for x in range(2010, 2027)] + ['2210']

          def gen_pass():
              # Genera diferentes estructuras de contraseña
              p_tipo = random.randint(1, 3)
              if p_tipo == 1: 
                  return random.choice(temas) + random.choice(anios) + random.choice(simbolos)
              elif p_tipo == 2: 
                  return random.choice(temas).lower() + random.choice(simbolos) + random.choice(anios)
              else: 
                  return random.choice(anios) + random.choice(temas) + random.choice(simbolos)

          lote_n = 1
          while lote_n <= 10: # Generará 10 millones en total (10 archivos de 1M)
              file_txt = f'passwords_lote_{lote_n}.txt'
              file_zip = f'noche_pass_{lote_n}.zip'
              
              print(f'[+] Iniciando Lote {lote_n}...')
              with open(file_txt, 'w') as f:
                  for _ in range(1000000):
                      f.write(gen_pass() + '\n')
              
              # Comprimir para que Telegram no lo rebote por peso
              with zipfile.ZipFile(file_zip, 'w', zipfile.ZIP_DEFLATED) as zipf:
                  zipf.write(file_txt)
              
              print(f'[->] Enviando {file_zip} a Telegram...')
              url = f'https://api.telegram.org/bot{TOKEN_TG}/sendDocument'
              try:
                  with open(file_zip, 'rb') as f_zip:
                      requests.post(url, data={'chat_id': CHAT_ID, 'caption': f'🔐 Lote {lote_n} generado con éxito'}, files={'document': f_zip})
              except:
                  print('Error de red al enviar.')

              # Limpieza de archivos temporales
              os.remove(file_txt)
              os.remove(file_zip)
              
              lote_n += 1
              time.sleep(2)
          "
